name: ArchitectureReference
options:
  bundleIdPrefix: com.dimaswisodewo
targets:
  ArchitectureReference:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: ArchitectureReference
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dimaswisodewo.ArchitectureReference
        DEVELOPMENT_TEAM: 4W4394L277
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: Alamofire
  ArchitectureReferenceTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: ArchitectureReferenceTests
    dependencies:
      - target: ArchitectureReference
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.12.0
